---
title: "Diagonalización"
author: "Martin Santamaria"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
Sys.setenv(RETICULATE_PYTHON = "/Python38")
library(reticulate)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(engine.path = list(octave = "/Octave/Octave-5.2.0/mingw64/bin/octave-cli-5.2.0.exe"))
```

### En `R`

```{r}
A = rbind(c(2,-2,1),c(2,-8,-2),c(1,2,2))
isSymmetric(A)
eig = eigen(A)

eig$values
l1 = eig$values[1]

eig$vectors
v1 = eig$vectors[,1]

A%*%v1
l1*v1

library(dplyr)
near(A%*%v1, l1*v1)

round(solve(eig$vectors)%*%A%*%eig$vectors,3)
```

### En `Python`

```{python}
import numpy as np
from numpy import linalg as la

A = np.array([[2,-2,1],[2,-8,-2],[1,2,2]])
A

w, v = la.eig(A)
w
v

l1 = w[0]
v1 = v[:,0]

l1
v1

np.isclose(np.dot(A,v1), l1*v1)
```

### En `Octave`

```{octave}
A = [[2,-2,1];[2,-8,-2];[1,2,2]];
A

[V, l] = eig(A)

inv(V)*A*V

A*V

l(1,1)*V(:,1)
l(2,2)*V(:,2)

V*l

eq(A*V, V*l)

A*V - V*l

eps

sum(sum(abs(A*V - V*l)))

le(sum(sum(abs(A*V - V*l))),sqrt(eps))

[V, l] = eig(A, "vector")
```

