---
title: "Determinantes"
author: "Martin Santamaria"
date: "27/5/2020"
output: html_document
---

```{r setup, include=FALSE}
Sys.setenv(RETICULATE_PYTHON = "/Python38")
library(reticulate)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(engine.path = list(octave = "/Octave/Octave-5.2.0/mingw64/bin/octave-cli-5.2.0.exe"))
```

### Determinantes

```{r}
A = rbind(c(1,2), c(0,-1))
det(A)
```

```{python}
import numpy as np
A = np.array([[1, 2], [0,-1]])
int(np.linalg.det(A))
```

```{octave}
A = [0 1 0 0 0 0 0 0; 1 0 2 0 0 0 0 0; 0 1 0 3 0 0 0 0; 0 0 1 0 4 0 0 0; 0 0 0 1 0 5 0 0; 0 0 0 0 1 0 6 0; 0 0 0 0 0 1 0 7; 0 0 0 0 0 0 1 0];
B = [0 1 0 0 0 0 0; 1 0 2 0 0 0 0; 0 1 0 3 0 0 0; 0 0 1 0 4 0 0; 0 0 0 1 0 5 0; 0 0 0 0 1 0 6; 0 0 0 0 0 1 0];
C = [0 1 0 0 0 0; 1 0 2 0 0 0; 0 1 0 3 0 0; 0 0 1 0 4 0; 0 0 0 1 0 5; 0 0 0 0 1 0];
D = [0 1 0 0 0; 1 0 2 0 0; 0 1 0 3 0; 0 0 1 0 4; 0 0 0 1 0];
E = [0 1 0 0; 1 0 2 0; 0 1 0 3; 0 0 1 0];
G = [0 1 0; 1 0 2; 0 1 0];
H = [0 1; 1 0];
det(A)
det(B)
det(C)
det(D)
det(E)
det(G)
det(H)
```

$a_1 - b_1$

$a_1a_2 - a_1b_2 + b_1b_2 - b_1a_2$

$a_1a_2a_3 + a_1b_2b_3 + b_1a_2b_3 + b_1b_2a_3 - a_1a_2b_3 - a_1b_2a_3 - b_1a_2a_3 - b_1b_2b_3$