---
title: "Tarea 4"
author: "Martin Santamaria"
date: "10/5/2020"
output: html_document
---

```{r setup, include=FALSE}
Sys.setenv(RETICULATE_PYTHON = "/Python38")
library(reticulate)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(engine.path = list(octave = "/Octave/Octave-5.2.0/mingw64/bin/octave-cli-5.2.0.exe"))
```

### Pregunta 1

##### En `R`

```{r}
A = matrix(c(0,1,-2,2,3,-1,1,-1,5), nrow = 3, ncol = 3, byrow = TRUE)
B = rbind(c(1,-1,2,1),c(2,-2,2,-2),c(-1,2,1,2))
C = cbind(c(2,0,1,-4))
A
B
C
```

```{r}
A%*%B
B%*%C
t(B)
t(B)%*%A
t(C)%*%t(B)
```

#### En `Python`

```{python}
import numpy as np

A = np.array([[0,1,-2], [2,3,-1], [1,-1,5]])
B = np.array([[1,-1,2,1], [2,-2,2,-2], [-1,2,1,2]])
C = np.array([[2], [0], [1], [-4]])
A
B
C
```

```{python}
A.dot(B)
B.dot(C)
B.transpose()
B.transpose().dot(A)
C.transpose().dot(B.transpose())
```

#### En `Octave`

```{octave}
A = [0 1 -2; 2 3 -1; 1 -1 5]
B = [1 -1 2 1; 2 -2 2 -2; -1 2 1 2]
C = [2;0;1;-4]

A*B
B*C
B'
B'*A
C'*B'
```

### Pregunta 2

##### En `R`

```{r}
A = rbind(c(0,1),c(0,1))
B = cbind(c(-1,0), c(-1,0))
A
B
```

```{r}
library(Biodem)

C = mtx.exp((A+B),2)
D = mtx.exp(A,2) + 2*(A%*%B) + mtx.exp(B,2)
C
D
C == D
```

#### En `Python`

```{python}
A = np.array([[0,1],[0,1]])
B = np.array([[-1,-1],[0,0]])
A
B
```

```{python}
C = np.linalg.matrix_power((A+B),3)
D = np.linalg.matrix_power(A,3) + 3*(np.linalg.matrix_power(A,2).dot(B)) + 3*(A.dot(np.linalg.matrix_power(B,2))) + np.linalg.matrix_power(B,3)
C
D
C == D
```

### Pregunta 3

#### En `Octave`

```{octave}
A = [-1 1 -2; 1 1 0; 2 1 1]
B = [-1 2 3 4 5; 1 2 1 3 2; 0 4 4 7 7]

rank(A)
rank(B)
```

### Pregunta 4

##### En `R`

```{r}
A = rbind(c(1,2,0),c(0,1,-1),c(0,0,2))
A
```

Verificamos primero si la matriz $A$ tiene inversa

```{r}
qr(A)$rank == 3
```

$\therefore$ la matriz $A$ tiene inversa

```{r}
solve(A)
```

#### En `Python`

```{python}
B = np.array([[1j,0,0], [0,0,1], [1,1j,0]])
B
```

Verificamos primero si la matriz $B$ tiene inversa

```{python}
np.linalg.matrix_rank(B) == 3
```

$\therefore$ la matriz $B$ tiene inversa

```{python}
np.linalg.inv(B)
```
