---
title: "Sistemas de Ecuaciones"
author: "Martin Santamaria"
date: "12/5/2020"
output: html_document
---

```{r setup, include=FALSE}
Sys.setenv(RETICULATE_PYTHON = "/Python38")
library(reticulate)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(engine.path = list(octave = "/Octave/Octave-5.2.0/mingw64/bin/octave-cli-5.2.0.exe"))
```

### Sistemas de ecuaciones

```{octave}
A = [1 2 1; 0 -3 1; 1 1 1]
B = [1 3 0; 0 2 0; -1 0 1]
C = [3 0 2; -2 1 -1; -1 1 2]
D = [1 3 5; 4 0 -2; 0 0 1]
X = [0.5 0 0; 4 -2 8; 15/2 -4 11]

E = (A*X)+B
F = (C*X) - X + D

E == F
```

```{r}
library(matlib)

A = rbind(c(1,1,2),c(2,4,-3),c(3,6,-5))
b = c(9,1,0)
AB = cbind(A,b)

showEqn(A,b)

plotEqn3d(A,b, xlim = c(-3,3), ylim = c(0,6))

Solve(A, b, fractions = TRUE)
echelon(AB, verbose = TRUE, fractions = T)

```

```{r}
A = rbind(c(0,4),c(2,1))
B = rbind(c(1,-1),c(2,3))
C = rbind(c(1,2),c(3,-2))
D = rbind(c(-2,1),c(-1,1))
I = diag(1, nrow = 2, ncol = 2)
M = A-(C+D)
N = 3*(D-B)+10*I
X = solve(M,N)
Z = solve(M)%*%N

X
Z
```

```{python}
from sympy import *
from sympy.solvers.solveset import linsolve
x,y,z = symbols('x,y,z')
x1,x2,x3 = symbols('x1,x2,x3')

linsolve([2*x1 + 2*x2 - 1, -x1 + x2 -2], (x1, x2))
```

```{python}
import matplotlib.pyplot as plt
import numpy as np

x1 = np.linspace(-10,10,100)
plt.plot(x1, 3/2-2*x1, x1, (x1/2)-1, x1, (1-3*x1)/4)
plt.show()

from mpl_toolkits.mplot3d import Axes3D

point1 = np.array([0,0,9/2])
n1 = np.array([1,1,2])

point2 = np.array([0,0,-1/3])
n2 = np.array([2,4,-3])

point3 = np.array([0,0,0])
n3 = np.array([3,6,-5])

D1 = -9
D2 = -1
D3 = 0

X, Y = np.meshgrid(range(30), range(30))

z1 = (-n1[0]*X - n1[1]*Y - D1)*1./n1[2]
z2 = (-n2[0]*X - n2[1]*Y - D2)*1./n2[2]
z3 = (-n3[0]*X - n3[1]*Y - D3)*1./n3[2]

plot3d = plt.figure().gca(projection='3d')
plot3d.plot_surface(X,Y,z1, color = 'red')
plot3d.plot_surface(X,Y,z2, color = 'cyan')
plot3d.plot_surface(X,Y,z3, color = 'yellow')
plt.show()
```

```{python}
A = np.array([[1,1],[1,-1],[2,1]])
AB = np.array([[1,1,2],[1,-1,1],[2,1,3]])
np.linalg.matrix_rank(A)
np.linalg.matrix_rank(AB)
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(AB)

x = np.linspace(0,2,100)
plt.plot(x, 2-x, x, x-1, x, 3-2*x)
plt.show()
```

```{octave}
A = [1 1; 1 -1; 2 1];
b = [2;1;3];
AB = [A b];
rank(A)
rank(AB)

rref(AB);

B = [2 0 0 0; 0 3 0 0; 0 0 4 0; 0 0 0 5];
D = [1 1 1; 1 1 0; 1 0 0];
inv(B)
inv(D);
E = diag([1 2 3 4 5 4 7 2])
inv(E)
A = [1 1 1; 0 -1 -1; -1 0 1]
linsolve(A,((sqrt(5)*A)*inv(A')))
inv(A)*(sqrt(5)*A)*inv(A')
```

